### ISSUE TITLE
Pop! Dark: Links to teal highlights and orange highlights are the same

### ISSUE THREAD

**Issue by cszach** [Webricolage/firefox-theme-pop-os#1]
The two links that supposedly provide 2 different highlight colors for the Pop! Dark theme are the same, which leads to a theme with teal highlights.

**Comment by cszach** [comment]
Perhaps this one is Pop! Dark with orange highlights?

https://color.firefox.com/?theme=XQAAAAL9AAAAAAAAAABBKYhm849SCia2CaaEGccwS-xNKlhZJHfv8ynOLL05Bb6lobcyXaJa6PpVsU3Ccld88BYb-IPM7JFfdhny4O-55e1XYxmnDy2L1RXMw9OpyGaHPOdMHzw2WjlXm3eFfPqGSyO8QBirJwqHuCleSQG2kOPUkcZ3kOFEQOQRoRra4Qp9kyvJFcUulZa9E95wPi_f1BKQdlg1sEmcYav9s_XA_GEmYuk9mJhPYv__85nIAA

**Comment by RubenSibon** [comment]
Thanks for the heads-up. I completely missed this issue. I hope to improve and fix the themes and the docs soon.

**Comment by RubenSibon** [comment]
I fixed it by remove those links all together. People can use the installable themes (.xpi).

**Comment by cszach** [comment]
Hey! Links are more convenient. Why remove them?

**Comment by RubenSibon** [comment]
I removed the links because with code changes to the installable themes the links have to be retroactively updated. As I am not using Firefox Color anymore and I felt it was too much work.

It is quite easy to make a Firefox Color theme yourself and you can always find the links in the commit history to have a starting point.
